// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateAccountRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{0}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateAccountRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type CreateAccountReply struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountReply) Reset()         { *m = CreateAccountReply{} }
func (m *CreateAccountReply) String() string { return proto.CompactTextString(m) }
func (*CreateAccountReply) ProtoMessage()    {}
func (*CreateAccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{1}
}

func (m *CreateAccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountReply.Unmarshal(m, b)
}
func (m *CreateAccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountReply.Marshal(b, m, deterministic)
}
func (m *CreateAccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountReply.Merge(m, src)
}
func (m *CreateAccountReply) XXX_Size() int {
	return xxx_messageInfo_CreateAccountReply.Size(m)
}
func (m *CreateAccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountReply proto.InternalMessageInfo

func (m *CreateAccountReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateAccountReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type SearchByCredsRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchByCredsRequest) Reset()         { *m = SearchByCredsRequest{} }
func (m *SearchByCredsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchByCredsRequest) ProtoMessage()    {}
func (*SearchByCredsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{2}
}

func (m *SearchByCredsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchByCredsRequest.Unmarshal(m, b)
}
func (m *SearchByCredsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchByCredsRequest.Marshal(b, m, deterministic)
}
func (m *SearchByCredsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchByCredsRequest.Merge(m, src)
}
func (m *SearchByCredsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchByCredsRequest.Size(m)
}
func (m *SearchByCredsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchByCredsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchByCredsRequest proto.InternalMessageInfo

func (m *SearchByCredsRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SearchByCredsRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type SearchByCredsReply struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchByCredsReply) Reset()         { *m = SearchByCredsReply{} }
func (m *SearchByCredsReply) String() string { return proto.CompactTextString(m) }
func (*SearchByCredsReply) ProtoMessage()    {}
func (*SearchByCredsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{3}
}

func (m *SearchByCredsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchByCredsReply.Unmarshal(m, b)
}
func (m *SearchByCredsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchByCredsReply.Marshal(b, m, deterministic)
}
func (m *SearchByCredsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchByCredsReply.Merge(m, src)
}
func (m *SearchByCredsReply) XXX_Size() int {
	return xxx_messageInfo_SearchByCredsReply.Size(m)
}
func (m *SearchByCredsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchByCredsReply.DiscardUnknown(m)
}

var xxx_messageInfo_SearchByCredsReply proto.InternalMessageInfo

func (m *SearchByCredsReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *SearchByCredsReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SearchByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchByIDRequest) Reset()         { *m = SearchByIDRequest{} }
func (m *SearchByIDRequest) String() string { return proto.CompactTextString(m) }
func (*SearchByIDRequest) ProtoMessage()    {}
func (*SearchByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{5}
}

func (m *SearchByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchByIDRequest.Unmarshal(m, b)
}
func (m *SearchByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchByIDRequest.Marshal(b, m, deterministic)
}
func (m *SearchByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchByIDRequest.Merge(m, src)
}
func (m *SearchByIDRequest) XXX_Size() int {
	return xxx_messageInfo_SearchByIDRequest.Size(m)
}
func (m *SearchByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchByIDRequest proto.InternalMessageInfo

func (m *SearchByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SearchByIDReply struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchByIDReply) Reset()         { *m = SearchByIDReply{} }
func (m *SearchByIDReply) String() string { return proto.CompactTextString(m) }
func (*SearchByIDReply) ProtoMessage()    {}
func (*SearchByIDReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{6}
}

func (m *SearchByIDReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchByIDReply.Unmarshal(m, b)
}
func (m *SearchByIDReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchByIDReply.Marshal(b, m, deterministic)
}
func (m *SearchByIDReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchByIDReply.Merge(m, src)
}
func (m *SearchByIDReply) XXX_Size() int {
	return xxx_messageInfo_SearchByIDReply.Size(m)
}
func (m *SearchByIDReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchByIDReply.DiscardUnknown(m)
}

var xxx_messageInfo_SearchByIDReply proto.InternalMessageInfo

func (m *SearchByIDReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *SearchByIDReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateAccountRequest)(nil), "pb.CreateAccountRequest")
	proto.RegisterType((*CreateAccountReply)(nil), "pb.CreateAccountReply")
	proto.RegisterType((*SearchByCredsRequest)(nil), "pb.SearchByCredsRequest")
	proto.RegisterType((*SearchByCredsReply)(nil), "pb.SearchByCredsReply")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*SearchByIDRequest)(nil), "pb.SearchByIDRequest")
	proto.RegisterType((*SearchByIDReply)(nil), "pb.SearchByIDReply")
}

func init() { proto.RegisterFile("users.proto", fileDescriptor_030765f334c86cea) }

var fileDescriptor_030765f334c86cea = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x1b, 0xd3, 0x22, 0xb8, 0x8a, 0x7f, 0x47, 0x41, 0x51, 0xc5, 0x80, 0xcc, 0xc2, 0x80,
	0x32, 0x94, 0x8d, 0x01, 0xa9, 0xa4, 0x0b, 0x6b, 0x10, 0x0f, 0x90, 0x3f, 0x27, 0x11, 0x29, 0x10,
	0x73, 0x4e, 0x84, 0xf2, 0x90, 0xbc, 0x13, 0xb2, 0x43, 0x68, 0x6a, 0x32, 0x65, 0x4b, 0xee, 0xee,
	0xfb, 0xee, 0xe7, 0xcf, 0x86, 0x79, 0xad, 0x89, 0x75, 0xa0, 0xb8, 0xac, 0x4a, 0x14, 0x2a, 0x91,
	0x8f, 0xb0, 0x08, 0x99, 0xe2, 0x8a, 0xd6, 0x69, 0x5a, 0xd6, 0x1f, 0x55, 0x44, 0x9f, 0x35, 0xe9,
	0x0a, 0x17, 0x30, 0xa3, 0xf7, 0x38, 0x2f, 0x7c, 0xef, 0xda, 0xbb, 0x3d, 0x8c, 0xda, 0x1f, 0x3c,
	0x85, 0x3d, 0xf5, 0x95, 0xf9, 0xc2, 0xd6, 0xcc, 0xa7, 0xdc, 0x00, 0x3a, 0x7a, 0x55, 0x34, 0x78,
	0x05, 0x53, 0xb3, 0xc8, 0x8a, 0xe7, 0xab, 0x83, 0x40, 0x25, 0xc1, 0xab, 0x26, 0x8e, 0x6c, 0xd5,
	0xb8, 0x10, 0x73, 0xe7, 0x42, 0xcc, 0x86, 0xe2, 0x85, 0x62, 0x4e, 0xdf, 0x9e, 0x9a, 0x90, 0x29,
	0xd3, 0x23, 0x28, 0x1c, 0xfd, 0x18, 0x8a, 0x3b, 0x98, 0x9a, 0x3e, 0x1e, 0x83, 0xc8, 0xb3, 0xdf,
	0x95, 0x22, 0xcf, 0xb6, 0x14, 0xa2, 0x47, 0x21, 0x6f, 0xe0, 0xac, 0xdb, 0xf9, 0xbc, 0xe9, 0x80,
	0x1d, 0xa9, 0x5c, 0xc3, 0x49, 0x7f, 0x68, 0x04, 0xd5, 0xea, 0xdb, 0x83, 0x99, 0x19, 0xd0, 0x18,
	0xc2, 0xd1, 0x4e, 0xd6, 0xe8, 0x1b, 0xf1, 0xd0, 0xf5, 0x2d, 0x2f, 0x07, 0x3a, 0xaa, 0x68, 0xe4,
	0xc4, 0x98, 0xec, 0x44, 0xd5, 0x9a, 0x0c, 0xa5, 0xdf, 0x9a, 0xfc, 0xcf, 0x55, 0x4e, 0xf0, 0x01,
	0x60, 0x7b, 0x2c, 0xbc, 0xe8, 0xcf, 0xfd, 0x65, 0xb1, 0x3c, 0x77, 0xcb, 0x56, 0x9b, 0xec, 0xdb,
	0xc7, 0x77, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x4a, 0xe8, 0xe5, 0x8b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountReply, error)
	SearchByCreds(ctx context.Context, in *SearchByCredsRequest, opts ...grpc.CallOption) (*SearchByCredsReply, error)
	SearchByID(ctx context.Context, in *SearchByIDRequest, opts ...grpc.CallOption) (*SearchByIDReply, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountReply, error) {
	out := new(CreateAccountReply)
	err := c.cc.Invoke(ctx, "/pb.Users/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) SearchByCreds(ctx context.Context, in *SearchByCredsRequest, opts ...grpc.CallOption) (*SearchByCredsReply, error) {
	out := new(SearchByCredsReply)
	err := c.cc.Invoke(ctx, "/pb.Users/SearchByCreds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) SearchByID(ctx context.Context, in *SearchByIDRequest, opts ...grpc.CallOption) (*SearchByIDReply, error) {
	out := new(SearchByIDReply)
	err := c.cc.Invoke(ctx, "/pb.Users/SearchByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountReply, error)
	SearchByCreds(context.Context, *SearchByCredsRequest) (*SearchByCredsReply, error)
	SearchByID(context.Context, *SearchByIDRequest) (*SearchByIDReply, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_SearchByCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchByCredsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).SearchByCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/SearchByCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).SearchByCreds(ctx, req.(*SearchByCredsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_SearchByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).SearchByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Users/SearchByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).SearchByID(ctx, req.(*SearchByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _Users_CreateAccount_Handler,
		},
		{
			MethodName: "SearchByCreds",
			Handler:    _Users_SearchByCreds_Handler,
		},
		{
			MethodName: "SearchByID",
			Handler:    _Users_SearchByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}
