// Code generated by protoc-gen-go. DO NOT EDIT.
// source: workbook.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreatePostRequest struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e40e2b6ce1228e38, []int{0}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type CreatePostReply struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostReply) Reset()         { *m = CreatePostReply{} }
func (m *CreatePostReply) String() string { return proto.CompactTextString(m) }
func (*CreatePostReply) ProtoMessage()    {}
func (*CreatePostReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e40e2b6ce1228e38, []int{1}
}

func (m *CreatePostReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostReply.Unmarshal(m, b)
}
func (m *CreatePostReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostReply.Marshal(b, m, deterministic)
}
func (m *CreatePostReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostReply.Merge(m, src)
}
func (m *CreatePostReply) XXX_Size() int {
	return xxx_messageInfo_CreatePostReply.Size(m)
}
func (m *CreatePostReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostReply proto.InternalMessageInfo

func (m *CreatePostReply) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *CreatePostReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Post struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Tags                 []*Tag   `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_e40e2b6ce1228e38, []int{2}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Tag struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_e40e2b6ce1228e38, []int{3}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*CreatePostRequest)(nil), "pb.CreatePostRequest")
	proto.RegisterType((*CreatePostReply)(nil), "pb.CreatePostReply")
	proto.RegisterType((*Post)(nil), "pb.Post")
	proto.RegisterType((*Tag)(nil), "pb.Tag")
}

func init() { proto.RegisterFile("workbook.proto", fileDescriptor_e40e2b6ce1228e38) }

var fileDescriptor_e40e2b6ce1228e38 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0xb2, 0xda, 0x76, 0x0a, 0x55, 0x47, 0x85, 0x45, 0x3d, 0x84, 0x3d, 0xc5, 0x4b,
	0xc0, 0x78, 0xf3, 0x26, 0x82, 0x67, 0x09, 0x05, 0xcf, 0x9b, 0x76, 0x09, 0xa1, 0x31, 0xb3, 0xee,
	0x8e, 0x48, 0xff, 0xbd, 0xec, 0xda, 0xa2, 0x18, 0xe8, 0x6d, 0xe6, 0x7b, 0xfb, 0xf6, 0x31, 0x0f,
	0x16, 0x5f, 0xe4, 0x36, 0x0d, 0xd1, 0xa6, 0xb4, 0x8e, 0x98, 0x30, 0xb5, 0x8d, 0xba, 0x87, 0xf3,
	0x67, 0x67, 0x34, 0x9b, 0x57, 0xf2, 0x5c, 0x9b, 0x8f, 0x4f, 0xe3, 0x19, 0x6f, 0x41, 0x58, 0xf2,
	0x2c, 0x93, 0x3c, 0x29, 0xe6, 0xd5, 0xb4, 0xb4, 0x4d, 0x19, 0xe5, 0x48, 0xd5, 0x13, 0x9c, 0xfe,
	0xb5, 0xd8, 0x7e, 0x7b, 0xd8, 0x80, 0x67, 0x90, 0x19, 0xe7, 0x64, 0x9a, 0x27, 0xc5, 0xac, 0x0e,
	0xa3, 0x5a, 0x81, 0x08, 0x3a, 0x2e, 0x20, 0xed, 0xd6, 0xd1, 0x35, 0xab, 0xd3, 0x6e, 0x8d, 0x97,
	0x70, 0xcc, 0x1d, 0xf7, 0x66, 0xf7, 0xf6, 0x67, 0x41, 0x09, 0x93, 0x15, 0x0d, 0x6c, 0x06, 0x96,
	0x59, 0xe4, 0xfb, 0x15, 0x6f, 0x40, 0xb0, 0x6e, 0xbd, 0x14, 0x79, 0x56, 0xcc, 0xab, 0x49, 0xc8,
	0x5d, 0xea, 0xb6, 0x8e, 0x50, 0xdd, 0x41, 0xb6, 0xd4, 0xed, 0x28, 0x03, 0x41, 0x0c, 0xfa, 0x7d,
	0x1f, 0x11, 0xe7, 0xea, 0x05, 0xa6, 0x6f, 0xbb, 0x6e, 0xf0, 0x11, 0xe0, 0xf7, 0x3c, 0xbc, 0x0a,
	0x7f, 0x8e, 0x1a, 0xba, 0xbe, 0xf8, 0x8f, 0x6d, 0xbf, 0x55, 0x47, 0xcd, 0x49, 0x2c, 0xf6, 0xe1,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0xca, 0x60, 0xd7, 0x04, 0x6a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkbookClient is the client API for Workbook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkbookClient interface {
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostReply, error)
}

type workbookClient struct {
	cc *grpc.ClientConn
}

func NewWorkbookClient(cc *grpc.ClientConn) WorkbookClient {
	return &workbookClient{cc}
}

func (c *workbookClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostReply, error) {
	out := new(CreatePostReply)
	err := c.cc.Invoke(ctx, "/pb.Workbook/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkbookServer is the server API for Workbook service.
type WorkbookServer interface {
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostReply, error)
}

func RegisterWorkbookServer(s *grpc.Server, srv WorkbookServer) {
	s.RegisterService(&_Workbook_serviceDesc, srv)
}

func _Workbook_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkbookServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Workbook/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkbookServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Workbook_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Workbook",
	HandlerType: (*WorkbookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _Workbook_CreatePost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workbook.proto",
}
