// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IssueTokensRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueTokensRequest) Reset()         { *m = IssueTokensRequest{} }
func (m *IssueTokensRequest) String() string { return proto.CompactTextString(m) }
func (*IssueTokensRequest) ProtoMessage()    {}
func (*IssueTokensRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *IssueTokensRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueTokensRequest.Unmarshal(m, b)
}
func (m *IssueTokensRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueTokensRequest.Marshal(b, m, deterministic)
}
func (m *IssueTokensRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueTokensRequest.Merge(m, src)
}
func (m *IssueTokensRequest) XXX_Size() int {
	return xxx_messageInfo_IssueTokensRequest.Size(m)
}
func (m *IssueTokensRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueTokensRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IssueTokensRequest proto.InternalMessageInfo

func (m *IssueTokensRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *IssueTokensRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type IssueTokensReply struct {
	Tokens               *Tokens  `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueTokensReply) Reset()         { *m = IssueTokensReply{} }
func (m *IssueTokensReply) String() string { return proto.CompactTextString(m) }
func (*IssueTokensReply) ProtoMessage()    {}
func (*IssueTokensReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *IssueTokensReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueTokensReply.Unmarshal(m, b)
}
func (m *IssueTokensReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueTokensReply.Marshal(b, m, deterministic)
}
func (m *IssueTokensReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueTokensReply.Merge(m, src)
}
func (m *IssueTokensReply) XXX_Size() int {
	return xxx_messageInfo_IssueTokensReply.Size(m)
}
func (m *IssueTokensReply) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueTokensReply.DiscardUnknown(m)
}

var xxx_messageInfo_IssueTokensReply proto.InternalMessageInfo

func (m *IssueTokensReply) GetTokens() *Tokens {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *IssueTokensReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Tokens struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Access               string   `protobuf:"bytes,2,opt,name=access,proto3" json:"access,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tokens) Reset()         { *m = Tokens{} }
func (m *Tokens) String() string { return proto.CompactTextString(m) }
func (*Tokens) ProtoMessage()    {}
func (*Tokens) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *Tokens) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tokens.Unmarshal(m, b)
}
func (m *Tokens) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tokens.Marshal(b, m, deterministic)
}
func (m *Tokens) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tokens.Merge(m, src)
}
func (m *Tokens) XXX_Size() int {
	return xxx_messageInfo_Tokens.Size(m)
}
func (m *Tokens) XXX_DiscardUnknown() {
	xxx_messageInfo_Tokens.DiscardUnknown(m)
}

var xxx_messageInfo_Tokens proto.InternalMessageInfo

func (m *Tokens) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Tokens) GetAccess() string {
	if m != nil {
		return m.Access
	}
	return ""
}

func init() {
	proto.RegisterType((*IssueTokensRequest)(nil), "pb.IssueTokensRequest")
	proto.RegisterType((*IssueTokensReply)(nil), "pb.IssueTokensReply")
	proto.RegisterType((*Tokens)(nil), "pb.Tokens")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xb2, 0xe1, 0x12, 0xf2, 0x2c,
	0x2e, 0x2e, 0x4d, 0x0d, 0xc9, 0xcf, 0x4e, 0xcd, 0x2b, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x11, 0x12, 0xe1, 0x62, 0x4d, 0xcd, 0x4d, 0xcc, 0xcc, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x82, 0x70, 0x84, 0x04, 0xb8, 0x98, 0x0b, 0xca, 0x53, 0x24, 0x98, 0xc0, 0x62, 0x20, 0xa6, 0x92,
	0x07, 0x97, 0x00, 0x8a, 0xee, 0x82, 0x9c, 0x4a, 0x21, 0x25, 0x2e, 0xb6, 0x12, 0x30, 0x17, 0xac,
	0x99, 0xdb, 0x88, 0x4b, 0xaf, 0x20, 0x49, 0x0f, 0xaa, 0x00, 0x2a, 0x03, 0x32, 0x29, 0xb5, 0xa8,
	0x08, 0x66, 0x52, 0x6a, 0x51, 0x91, 0x92, 0x11, 0x17, 0x5b, 0x08, 0x5c, 0xae, 0x34, 0x33, 0x05,
	0x6a, 0x33, 0x88, 0x29, 0x24, 0xc6, 0xc5, 0x96, 0x98, 0x9c, 0x9c, 0x5a, 0x5c, 0x0c, 0xd5, 0x00,
	0xe5, 0x19, 0xb9, 0x72, 0xb1, 0x38, 0x96, 0x96, 0x64, 0x08, 0xd9, 0x72, 0x71, 0x23, 0xb9, 0x42,
	0x48, 0x0c, 0x64, 0x21, 0xa6, 0xa7, 0xa4, 0x44, 0x30, 0xc4, 0x0b, 0x72, 0x2a, 0x95, 0x18, 0x92,
	0xd8, 0xc0, 0xa1, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x8a, 0x48, 0xe5, 0x1b, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	IssueTokens(ctx context.Context, in *IssueTokensRequest, opts ...grpc.CallOption) (*IssueTokensReply, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) IssueTokens(ctx context.Context, in *IssueTokensRequest, opts ...grpc.CallOption) (*IssueTokensReply, error) {
	out := new(IssueTokensReply)
	err := c.cc.Invoke(ctx, "/pb.Auth/IssueTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	IssueTokens(context.Context, *IssueTokensRequest) (*IssueTokensReply, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_IssueTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).IssueTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Auth/IssueTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).IssueTokens(ctx, req.(*IssueTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueTokens",
			Handler:    _Auth_IssueTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
